version: '3.8'

services:
  # ----------------------------
  # Servicio 1: Base de Datos
  # ----------------------------
  db:
    image: mysql:8.0
    container_name: gestor_academico_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DOCKER_DB_USER}
      MYSQL_PASSWORD: ${DOCKER_DB_PASSWORD}
    ports:
      - "${DOCKER_DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # ----------------------------
  # Servicio 2: API NestJS
  # ----------------------------
  api:
    build: .
    container_name: gestor_academico_api
    restart: always
    ports:
      - "${PORT}:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DOCKER_DB_USER}
      DB_PASSWORD: ${DOCKER_DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy

  # ----------------------------
  # Adminer
  # ----------------------------
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  mysql_data: